-- MySQL Script generated by MySQL Workbench
-- lun. 10 juil. 2017 10:11:42 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sql_quest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql_quest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql_quest` DEFAULT CHARACTER SET utf8 ;
USE `sql_quest` ;

-- -----------------------------------------------------
-- Table `sql_quest`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_quest`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql_quest`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_quest`.`organization` (
  `idorganization` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `website_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorganization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql_quest`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_quest`.`content` (
  `idcontent` INT NOT NULL AUTO_INCREMENT,
  `tweet` VARCHAR(45) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idcontent`, `user_iduser`),
  INDEX `fk_content_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_content_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `sql_quest`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql_quest`.`user_has_organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_quest`.`user_has_organization` (
  `user_iduser` INT NOT NULL,
  `organization_idorganization` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `organization_idorganization`),
  INDEX `fk_user_has_organization_organization1_idx` (`organization_idorganization` ASC),
  INDEX `fk_user_has_organization_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_organization_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `sql_quest`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_organization_organization1`
    FOREIGN KEY (`organization_idorganization`)
    REFERENCES `sql_quest`.`organization` (`idorganization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
